//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmployeWorkingStatus
    {
        public int status_id { get; set; }
        public Nullable<int> status_emp_fk { get; set; }
        public Nullable<int> status_dep_fk { get; set; }
        public Nullable<int> status_year { get; set; }
        public Nullable<double> status_basicSalary { get; set; }
        public Nullable<double> status_bonus { get; set; }
        public Nullable<double> status_medical { get; set; }
        public Nullable<int> staus_casualLeave { get; set; }
        public Nullable<int> staus_sickLeave { get; set; }
        public Nullable<int> staus_halfDays { get; set; }
        public Nullable<int> staus_anualLeave { get; set; }
    
        public virtual tbl_departments tbl_departments { get; set; }
        public virtual tbl_employee tbl_employee { get; set; }
    }
}
