//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public tbl_employee()
        {
            this.tbl_EmployeWorkingStatus = new HashSet<tbl_EmployeWorkingStatus>();
        }
    
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_contact { get; set; }
        public string emp_cnic { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_image { get; set; }
        public Nullable<bool> emp_gender { get; set; }
        public string emp_email { get; set; }
        public Nullable<System.DateTime> emp_hireDate { get; set; }
        public Nullable<bool> emp_status { get; set; }
    
        public virtual ICollection<tbl_EmployeWorkingStatus> tbl_EmployeWorkingStatus { get; set; }
    }
}
