//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_departments
    {
        public tbl_departments()
        {
            this.tbl_EmployeWorkingStatus = new HashSet<tbl_EmployeWorkingStatus>();
        }
    
        public int dept_id { get; set; }
        public string dept_name { get; set; }
    
        public virtual ICollection<tbl_EmployeWorkingStatus> tbl_EmployeWorkingStatus { get; set; }
    }
}
