//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback
    {
        public int fb_id { get; set; }
        public string fb_name { get; set; }
        public string fb_phone { get; set; }
        public string fb_email { get; set; }
        public string fb_company { get; set; }
        public string fb_feedback { get; set; }
    }
}
